
title: Code Rink
email: blog@mail.pindej.cz
description: >- # this means to ignore newlines until "baseurl:"
  My personal tech and development blog. All opinions are mine and mine only.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.pindej.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/site-logo.png"

twitter_username: fdpindej
github_username:  fpindej
linkedin_username: fpindej

# Build settings
theme: jekyll-theme-so-simple
# skin: "/assets/css/skins/dark.css"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

read_time: true
words_per_minute: 200

paginate: 3  # amount of posts to show per page
paginate_path: /page:num/

search_full_content: true

# Site Author
author:
  name: Filip Dorian Pindej
  picture: /assets/img/filip-pindej.jpg
  email: blog@mail.pindej.cz
  twitter: fdpindej
  links:
    - title: Twitter
      url: https://twitter.com/fdpindej
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/fpindej
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://www.linkedin.com/in/filip-dorian-pindej/
      icon: fab fa-linkedin-square

copyright: "Made by Filip Dorian Pindej."